## Pandas -> open source python library (library -> is collection of modules )
## used for ->
- data manipulation
- analysis

# installing pandas

In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\91790\appdata\roaming\python\python310\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.22.4 in c:\users\91790\appdata\roaming\python\python310\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\91790\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\91790\appdata\roaming\python\python310\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\91790\appdata\roaming\python\python310\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\91790\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# importing pandas

In [7]:
import pandas as pd                           # as pd -> alias

# to check version of pandas

In [8]:
pd.__version__

'2.3.2'

# Key Data Structure
 - Series = one list (tb of single column only)
 - Data Frame = full table

# Pandas Series

## Create series

In [15]:
series_exam = pd.Series([3,4,5])                        # Series ✔️              series ❌          
# list and tuple -> both works

In [16]:
series_examp

0    3
1    4
2    5
dtype: int64

## Indexing and slicing

In [24]:
#  var[ idx ]

series_exam[1]

np.int64(4)

In [25]:
# var[ start_idx , end_idx ]     ->  end_idx - not included

series_exam[0:2]

0    3
1    4
dtype: int64

## Series Atrributes

In [26]:
series_exam.index

RangeIndex(start=0, stop=3, step=1)

In [27]:
series_exam.values

array([3, 4, 5])

In [29]:
series_exam.dtype

dtype('int64')

In [77]:
series_exam.shape

(3,)

## Series Methods

### .head(n)  ->   number of samples u want from top    ->   by default 5

In [30]:
series_exam.head()

0    3
1    4
2    5
dtype: int64

In [32]:
series_exam.head(2)

0    3
1    4
dtype: int64

### .tail(n)  ->   number of samples u want from bottom    ->  by default 5

In [34]:
series_exam.tail()

0    3
1    4
2    5
dtype: int64

In [35]:
series_exam.tail(1)

2    5
dtype: int64

### .sort_values()    ->    sorts the values   ->   by default  -  ascending  
### .sort_values(ascending =False)    -> descending order

In [42]:
series_exam1 = pd.Series([5,3,9,4,56,1,3,23])

In [43]:
series_exam1

0     5
1     3
2     9
3     4
4    56
5     1
6     3
7    23
dtype: int64

In [44]:
series_exam1.sort_values()

5     1
1     3
6     3
3     4
0     5
2     9
7    23
4    56
dtype: int64

In [46]:
series_exam1.sort_values(ascending=False)

4    56
7    23
2     9
0     5
3     4
1     3
6     3
5     1
dtype: int64

###  .count()    -> return number of samples

In [47]:
series_exam1.count()

np.int64(8)

###  .isnull()    ->    checks for presence of null values

In [48]:
series_exam1.isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

###     .notnull()       ->   check for samples that are not null

In [49]:
series_exam1.notnull()

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
dtype: bool

## Operations  ( + , - , * , / , **)

In [53]:
series_exam1

0     5
1     3
2     9
3     4
4    56
5     1
6     3
7    23
dtype: int64

In [52]:
series_exam1 + 2

0     7
1     5
2    11
3     6
4    58
5     3
6     5
7    25
dtype: int64

In [54]:
series_exam1 * 2

0     10
1      6
2     18
3      8
4    112
5      2
6      6
7     46
dtype: int64

## Missing Values

In [55]:
series_with_missing_val = pd.Series([2,None,5])

In [56]:
series_with_missing_val

0    2.0
1    NaN
2    5.0
dtype: float64

###    .isnull()

In [57]:
series_with_missing_val.isnull()

0    False
1     True
2    False
dtype: bool

### fillna()  ->  to fill  values in place of Nan

- when dealing with numerical data - we fill 0

In [59]:
series_with_missing_val.fillna(0)

0    2.0
1    0.0
2    5.0
dtype: float64

-- now we filled 0 in place of Nan - let's check our dataset

In [60]:
series_with_missing_val = series_with_missing_val.fillna(0)

In [61]:
series_with_missing_val

0    2.0
1    0.0
2    5.0
dtype: float64

## Creating index 
### pd.Series( data=[  ] , index = list(" ") )  
-->  no. of vales in data = in index

In [63]:
series_idx = pd.Series(data=[100,200,300,400,500] , index = list('abcde'))

In [64]:
series_idx

a    100
b    200
c    300
d    400
e    500
dtype: int64

# DataFrame   -> table  -> collection of rows and column
-- dictionary -> key - value pair

In [147]:
dataset = pd.DataFrame({ 
            "Name" : ["Ram" , "Shyam" ],
            "Age" : [21 , 19]
})

In [67]:
dataset

    Name  Age
0    Ram   21
1  Shyam   19

--         DataFame ->  in general  collection of columns with a collection of values(c/a as rows)

## Creating DataFrame using collection of Series

In [68]:
series1 = pd.Series(data=[1,2,3,4,5])

In [69]:
series2 = pd.Series (data = [10,20,30,40,50])

In [72]:
series3_with_idx = pd.Series(data= [100,200,300,400,500] , index =list("abcde"))

In [74]:
df = pd.DataFrame({
    "c1" : series1,
    "c2" : series2 })

In [75]:
df

   c1  c2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

## DataFrame Attributes

In [78]:
df.shape

(5, 2)

In [79]:
df.columns

Index(['c1', 'c2'], dtype='object')

In [81]:
df.dtypes

c1    int64
c2    int64
dtype: object

## Accessing Data

### using labels

### df.loc[ row_no. , colname ]   -> if idx was not number then [ row_label , col_label]

In [84]:
df.loc[1,"c1"]

np.int64(2)

### using index
### df.iloc[ row_no., col_idx ]

In [88]:
df.iloc[1,0]

np.int64(2)

In [90]:
df.loc[0]

c1     1
c2    10
Name: 0, dtype: int64

In [91]:
df.iloc[0]

c1     1
c2    10
Name: 0, dtype: int64

## DataFrame Methods

### df.head(n)

In [93]:
df.head(4)

   c1  c2
0   1  10
1   2  20
2   3  30
3   4  40

### df.tail(n)

In [94]:
df.tail(3)

   c1  c2
2   3  30
3   4  40
4   5  50

### df.info()   ->  gives all info abt DataFrame including ( ranges , non null count , dtype , m/m usage , etc)

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c1      5 non-null      int64
 1   c2      5 non-null      int64
dtypes: int64(2)
memory usage: 208.0 bytes

### df.describe()    ->   gives all stats of numeric attribute

In [103]:
df.describe()

             c1         c2
count  5.000000   5.000000
mean   3.000000  30.000000
std    1.581139  15.811388
min    1.000000  10.000000
25%    2.000000  20.000000
50%    3.000000  30.000000
75%    4.000000  40.000000
max    5.000000  50.000000

### df.count()  ->  returns number of samples

In [106]:
df.count()

c1    5
c2    5
dtype: int64

### df.sort_values("col")

In [115]:
df.sort_values("c2",ascending=False)

   c1  c2
4   5  50
3   4  40
2   3  30
1   2  20
0   1  10

## Filtering

### df["col"]>val                  # returns bool  ( aisa hai kya -> True or False)

In [117]:
df["c1"]>3                  # returns bool  ( aisa hai kya -> True or False)

0    False
1    False
2    False
3     True
4     True
Name: c1, dtype: bool

### df[df["col"]>val]                          # returns DataFrame  ( jinke sath aisa hai  -->  unko return krdo) ( TRUE )

In [118]:
df[df["c1"]>3]                          # returns DataFrame  ( jinke sath aisa hai  -->  unko return krdo) ( TRUE )

   c1  c2
3   4  40
4   5  50

In [119]:
df[df["c1"]==2]

   c1  c2
1   2  20

In [120]:
df[df["c2"]!=50]

   c1  c2
0   1  10
1   2  20
2   3  30
3   4  40

## Adding , Updating , Deleting

In [121]:
df

   c1  c2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

### adding column  -->    df["nw_col"] = [val1,val2,--]

In [122]:
df["tips"]=[5,9,7,1,8]

In [123]:
df

   c1  c2  tips
0   1  10     5
1   2  20     9
2   3  30     7
3   4  40     1
4   5  50     8

### deleting a column  -->  del df["col_name"]

In [125]:
del df["tips"]

In [126]:
df

   c1  c2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

In [127]:
df["tips"]=[5,7,3,3,9]

In [128]:
df

   c1  c2  tips
0   1  10     5
1   2  20     7
2   3  30     3
3   4  40     3
4   5  50     9

### deleting (DROPPING) a column -->  df=df.drop(columns-["col_name"])

In [129]:
df=df.drop(columns=["tips"])

In [130]:
df

   c1  c2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

### deleting multiple columns

In [131]:
# df=df.drop(columns=["col1","col2"]

### ignoring errrors while deleting

In [132]:
# df=df.drop(columns=["col1","col2"] , errors = ignore)

### inplace (del from original df)

In [133]:
# df.drop(columns=["col1","col2"] , inplace =True)

### Updating

In [134]:
dataset

    Name  Age
0    Ram   21
1  Shyam   19

dataset

### updating vlaue in particular col
### df.loc[df["col"]==val,"col_for_change"]=new_val

In [149]:
dataset.loc[dataset["Name"]=="Ram","Age"]=27

In [150]:
dataset

    Name  Age
0    Ram   27
1  Shyam   19

### updating value in all columns
### df.loc[df["col"]==val]=new_val

In [152]:
dataset.loc[dataset["Name"]=="Ram"]=29

In [153]:
dataset

    Name  Age
0     29   29
1  Shyam   19

### Renaming

In [154]:
df

   c1  c2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

In [159]:
df.rename(columns={"c1":"column1","c2":"column2"},inplace=True)

In [160]:
df

   column1  column2
0        1       10
1        2       20
2        3       30
3        4       40
4        5       50

## Indexing and Selection

### Set column as an index -> index can be int , string
- df.set_index("colname",inplace=True)

In [161]:
df.set_index("column1",inplace=True)

In [162]:
df

         column2
column1
1             10
2             20
3             30
4             40
5             50

In [165]:
df.loc[4,"column2"]

np.int64(40)

In [168]:
df.iloc[3,0]

np.int64(40)

In [188]:
df["alpha"]=["a","e","i","o","u"]

In [189]:
df

       column2 alpha
alpha
a           10     a
e           20     e
i           30     i
o           40     o
u           50     u

In [190]:
df.set_index("alpha",inplace=True)

In [192]:
df

       column2
alpha
a           10
e           20
i           30
o           40
u           50

In [194]:
df.loc["e","column2"]               # accessing value using labels

np.int64(20)

In [195]:
df.iloc[3,0]

np.int64(40)

### RESET idx
### df.reset_index(inplace=True)

In [180]:
df.reset_index(inplace=True)

In [181]:
df

  alpha  column2
0     a       10
1     e       20
2     i       30
3     o       40
4     u       50

### Multiple index

In [247]:
multiple_dataset = pd.DataFrame({
    "Park":["A","A","B","B"],
    "Name":["Anna","Ben","Chris","Daisy"],
    "badminton":[2,3,4,5]
})

In [248]:
multiple_dataset

  Park   Name  badminton
0    A   Anna          2
1    A    Ben          3
2    B  Chris          4
3    B  Daisy          5

In [258]:
multiple_dataset.set_index(["Park","Name"],inplace=True)

In [260]:
multiple_dataset

            index  badminton
Park Name
A    Anna       0          2
     Ben        1          3
B    Chris      2          4
     Daisy      3          5

In [264]:
multiple_dataset.drop(columns=["index"],inplace=True)

## Selecting with conditions

In [270]:
multiple_dataset[multiple_dataset.badminton>=3]

            badminton
Park Name
A    Ben            3
B    Chris          4
     Daisy          5

## Selecting with query

In [269]:
multiple_dataset.query(" badminton > 3 ")

            badminton
Park Name
B    Chris          4
     Daisy          5

# Working with data

## converting our data to a csv file

In [271]:
multiple_dataset.to_csv("badminton.csv")

## reading data from file

In [273]:
data1 = pd.read_csv("badminton.csv")

In [274]:
data1

  Park   Name  badminton
0    A   Anna          2
1    A    Ben          3
2    B  Chris          4
3    B  Daisy          5

## Creating DataFrame using dictionary

### passing heterogeneous values in dictionary to form a dataframe

In [276]:
import numpy as np

In [280]:
dict = {"x":[1,2,3],                         # list
        "y":np.array([10,20,30]),             # numpy array
        "z":50
       }                                     # integer

In [279]:
pd.DataFrame(dict)

   x   y   z
0  1  10  50
1  2  20  50
2  3  30  50

### ALL arrays must be of same length

d={"x":[1,2,3],                    # EROOR
   "y":[10,20,30,40],
   "z":50
  }
df=pd.DataFrame(d)

## Creating DataFrame using lists

In [285]:
lists = [[1,2,3,4] , [32,45,56,67] , [2,8,9,12]]

df=pd.DataFrame(lists,columns=["w","x","y","z"] )

In [286]:
df

    w   x   y   z
0   1   2   3   4
1  32  45  56  67
2   2   8   9  12

## Creating DataFrame using numpy array

In [288]:
narr = np.array([[1,2,3],
                 [10,20,45],
                 [100,150,230]
    ])

d_f = pd.DataFrame(narr,columns=["a","b","c"])

In [289]:
d_f

     a    b    c
0    1    2    3
1   10   20   45
2  100  150  230

# Date Cleaning and Preprocessing

## Handling Missing Values
- .isnull()
- .notnull()
- .fillna(0)
-  dropna()

In [317]:
missing_data = pd.DataFrame({
                "x":[1,2,3,None],
                "y":["a",None,"c","e"],
                "z":[40,56,23,None]
})

In [318]:
missing_data

     x     y     z
0  1.0     a  40.0
1  2.0  None  56.0
2  3.0     c  23.0
3  NaN     e   NaN

### checking for isnull

In [319]:
missing_data.isnull()

       x      y      z
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

In [320]:
missing_data["x"].dtype

dtype('float64')

In [321]:
missing_data["y"].dtype

dtype('O')

In [322]:
missing_data["z"].dtype

dtype('float64')

## filling nulls as per column data type ->  numeric - 0 ; object - "none"

In [323]:
missing_data[["x","z"]]=missing_data[["x","z"]].fillna(0)
missing_data["y"]=missing_data["y"].fillna("None")

missing_data

     x     y     z
0  1.0     a  40.0
1  2.0  None  56.0
2  3.0     c  23.0
3  0.0     e   0.0

- i want to see how each method works, so not making changes in original df i.e. skipping inplace for now

In [297]:
missing_data.fillna(0)

     x  y     z
0  1.0  a  40.0
1  2.0  0  56.0
2  3.0  c  23.0
3  0.0  e   0.0

In [324]:
missing_data

     x     y     z
0  1.0     a  40.0
1  2.0  None  56.0
2  3.0     c  23.0
3  0.0     e   0.0

### .dropna()   -> remove rows having Nan in their columns

In [325]:
# missing_data.dropna()

# Aggregation

In [330]:
missing_data_agg = pd.DataFrame({
                "x":[1,2,3,None],
                "y":["a",None,"c","e"],
                "z":[40,56,23,None]
})

In [331]:
missing_data_agg

     x     y     z
0  1.0     a  40.0
1  2.0  None  56.0
2  3.0     c  23.0
3  NaN     e   NaN

### finding mean for a column -> df["col"].mean()

In [334]:
missing_data_agg["x"].mean()

np.float64(2.0)

### now i want to fill nan with mean i.e average value

In [335]:
missing_data_agg["x"].fillna(missing_data["x"].mean())        # temporary fill

0    1.0
1    2.0
2    3.0
3    1.5
Name: x, dtype: float64

In [336]:
missing_data_agg

     x     y     z
0  1.0     a  40.0
1  2.0  None  56.0
2  3.0     c  23.0
3  NaN     e   NaN

In [338]:
missing_data_agg["x"].fillna(missing_data_agg["x"].min())            # temporary fill

0    1.0
1    2.0
2    3.0
3    1.0
Name: x, dtype: float64

# Removing duplicates

In [37]:
import pandas as pd
df1=pd.DataFrame({
    "x":[1,2,1,1],
    "y":[10,10,10,10],
    "z":[11,2,11,11]
})
df1

   x   y   z
0  1  10  11
1  2  10   2
2  1  10  11
3  1  10  11

### To check for duplicates -> give true false as one column
### df.duplicated()

In [38]:
df1.duplicated()

0    False
1    False
2     True
3     True
dtype: bool

### Removing duplicates
### df.drop_duplicates()

In [39]:
df1.drop_duplicates()

   x   y   z
0  1  10  11
1  2  10   2

In [40]:
df1

   x   y   z
0  1  10  11
1  2  10   2
2  1  10  11
3  1  10  11

## Replacing values

In [41]:
df1.replace(1,100,inplace=True)

In [42]:
df1

     x   y   z
0  100  10  11
1    2  10   2
2  100  10  11
3  100  10  11

## Type Conversion

- Let's check what dtypes we have in our dataset

In [43]:
df1.dtypes

x    int64
y    int64
z    int64
dtype: object

- let's change from float to int

### remember before type conversion - first handle nans

In [44]:
df1.replace(1,100,inplace=True)

### converting int to float

In [45]:
df1[["x","y","z"]]=df1[["x","y","z"]].astype(float)

In [46]:
df1.dtypes

x    float64
y    float64
z    float64
dtype: object

#  String operations

In [51]:
df1["label"]=["yes","no","yes","no"]

In [52]:
df1

       x     y     z label
0  100.0  10.0  11.0   yes
1    2.0  10.0   2.0    no
2  100.0  10.0  11.0   yes
3  100.0  10.0  11.0    no

### string to uppercase -> df["strcol"].str.upper()

In [53]:
df1["label"].str.upper()

0    YES
1     NO
2    YES
3     NO
Name: label, dtype: object

### string to lowercase -> df["strcol"].str.lower()

In [54]:
df1["label"].str.lower()

0    yes
1     no
2    yes
3     no
Name: label, dtype: object

# Data Aggregation and Grouping

In [55]:
df1

       x     y     z label
0  100.0  10.0  11.0   yes
1    2.0  10.0   2.0    no
2  100.0  10.0  11.0   yes
3  100.0  10.0  11.0    no

### grouping Data -> df.groupby("col")

In [67]:
grouped_df1=df1.groupby("label")
grouped_df1.sum()

           x     y     z
label
no     102.0  20.0  13.0
yes    200.0  20.0  22.0

In [65]:
grouped_df1

## Aggregation -> grouped_df["numeiral_col"].aggregation_function

- aggregation on particular column

In [72]:
grouped_df1["y"].mean()

label
no     10.0
yes    10.0
Name: y, dtype: float64

- aggregation on all columns

In [73]:
grouped_df1.mean()

           x     y     z
label
no      51.0  10.0   6.5
yes    100.0  10.0  11.0

# Pivot Table -> calculates avg for each column

In [79]:
df1.pivot_table(values=["x","y","z"],index="label")

           x     y     z
label
no      51.0  10.0   6.5
yes    100.0  10.0  11.0

## Cross tab -> used to check presence of values

In [83]:
pd.crosstab(df1["label"],df1["x"])

x      2.0    100.0
label
no         1      1
yes        0      2

# Merging , Joining , Concatenating

### NOw we will require 2 tables or dataframes

In [87]:
data1 = pd.DataFrame({
        "c1":["a","e","i","o","u"],
        "c2":[12,34,56,67,87],
        "c3":[21,43,65,87,90]
})
data1

  c1  c2  c3
0  a  12  21
1  e  34  43
2  i  56  65
3  o  67  87
4  u  87  90

In [101]:
data2 = pd.DataFrame({
        "c1":["a","e","i","o","u"],
        "d2":[21,43,65,43,123],
        "c3":[98,112,200,150,100]
})
data2

  c1   d2   c3
0  a   21   98
1  e   43  112
2  i   65  200
3  o   43  150
4  u  123  100

## Concatenate
- common column -> appear ones
- if no column in

In [102]:
pd.concat([data1,data2])

  c1    c2   c3     d2
0  a  12.0   21    NaN
1  e  34.0   43    NaN
2  i  56.0   65    NaN
3  o  67.0   87    NaN
4  u  87.0   90    NaN
0  a   NaN   98   21.0
1  e   NaN  112   43.0
2  i   NaN  200   65.0
3  o   NaN  150   43.0
4  u   NaN  100  123.0

## Merging

In [116]:
small_data1=pd.DataFrame({
    "col1":["id1","id2","id3","id4","id5"],
    "col2":[1,2,3,4,5],
    "col3":[5,4,3,2,1]
})
small_data1

  col1  col2  col3
0  id1     1     5
1  id2     2     4
2  id3     3     3
3  id4     4     2
4  id5     5     1

In [117]:
small_data2=pd.DataFrame({
    "col1":["id1","id2","id3","id4","id7"],
    "col2":[1,2,3,4,5],
    "col4":[15,24,31,26,17]
})
small_data2

  col1  col2  col4
0  id1     1    15
1  id2     2    24
2  id3     3    31
3  id4     4    26
4  id7     5    17

In [118]:
pd.merge(small_data1,small_data2,on="col1")

  col1  col2_x  col3  col2_y  col4
0  id1       1     5       1    15
1  id2       2     4       2    24
2  id3       3     3       3    31
3  id4       4     2       4    26

## join on index

In [123]:
small_data1.join(small_data2.set_index("col1"), on="col1",lsuffix="_left",rsuffix="_right")

  col1  col2_left  col3  col2_right  col4
0  id1          1     5         1.0  15.0
1  id2          2     4         2.0  24.0
2  id3          3     3         3.0  31.0
3  id4          4     2         4.0  26.0
4  id5          5     1         NaN   NaN

# Working with TimeSeries

In [45]:
import pandas as pd

dataset1 = pd.read_csv("Orders.csv")

In [47]:
dataset1

,OrderID,ProductID,CustomerID,SalesPersonID,OrderDate,ShipDate,OrderStatus,ShipAddress,BillAddress,Quantity,Sales,CreationTime
0,1,101,2,3,2025-01-01,2025-01-05,Delivered,9833 Mt. Dias Blv.,1226 Shoe St.,1,10,2025-01-01 12:34:56.0000000
1,2,102,3,3,2025-01-05,2025-01-10,Shipped,250 Race Court,NaN,1,15,2025-01-05 23:22:04.0000000
2,3,101,1,5,2025-01-10,2025-01-25,Delivered,8157 W. Book,8157 W. Book,2,20,2025-01-10 18:24:08.0000000
3,4,105,1,3,2025-01-20,2025-01-25,Shipped,5724 Victory Lane,NaN,2,60,2025-01-20 05:50:33.0000000
4,5,104,2,5,2025-02-01,2025-02-05,Delivered,NaN,NaN,1,25,2025-02-01 14:02:41.0000000
5,6,104,3,5,2025-02-05,2025-02-10,Delivered,1792 Belmont Rd.,NaN,2,50,2025-02-06 15:34:57.0000000
6,7,102,1,1,2025-02-15,2025-02-27,Delivered,136 Balboa Court,NaN,2,30,2025-02-16 06:22:01.0000000
7,8,101,4,3,2025-02-18,2025-02-27,Shipped,2947 Vine Lane,4311 Clay Rd,3,90,2025-02-18 10:45:22.0000000
8,9,101,2,3,2025-03-10,2025-03-15,Shipped,3768 Door Way,NaN,2,20,2025-03-10 12:59:04.0000000
9,10,102,3,5,2025-03-15,2025-03-20,Shipped,NaN,NaN,0,60,2025-03-16 23:25:15.0000000

In [49]:
dataset1.count()

OrderID          10
ProductID        10
CustomerID       10
SalesPersonID    10
OrderDate        10
ShipDate         10
OrderStatus      10
ShipAddress       8
BillAddress       3
Quantity         10
Sales            10
CreationTime     10
dtype: int64

In [50]:
dataset1["BillAddress"].isnull()

0    False
1     True
2    False
3     True
4     True
5     True
6     True
7    False
8     True
9     True
Name: BillAddress, dtype: bool

In [53]:
dataset1["BillAddress"]=dataset["BillAddress"].fillna("None")

In [55]:
dataset1

,OrderID,ProductID,CustomerID,SalesPersonID,OrderDate,ShipDate,OrderStatus,ShipAddress,BillAddress,Quantity,Sales,CreationTime
0,1,101,2,3,2025-01-01,2025-01-05,Delivered,9833 Mt. Dias Blv.,NaN,1,10,2025-01-01 12:34:56.0000000
1,2,102,3,3,2025-01-05,2025-01-10,Shipped,250 Race Court,NaN,1,15,2025-01-05 23:22:04.0000000
2,3,101,1,5,2025-01-10,2025-01-25,Delivered,8157 W. Book,NaN,2,20,2025-01-10 18:24:08.0000000
3,4,105,1,3,2025-01-20,2025-01-25,Shipped,5724 Victory Lane,NaN,2,60,2025-01-20 05:50:33.0000000
4,5,104,2,5,2025-02-01,2025-02-05,Delivered,NaN,NaN,1,25,2025-02-01 14:02:41.0000000
5,6,104,3,5,2025-02-05,2025-02-10,Delivered,1792 Belmont Rd.,NaN,2,50,2025-02-06 15:34:57.0000000
6,7,102,1,1,2025-02-15,2025-02-27,Delivered,136 Balboa Court,NaN,2,30,2025-02-16 06:22:01.0000000
7,8,101,4,3,2025-02-18,2025-02-27,Shipped,2947 Vine Lane,NaN,3,90,2025-02-18 10:45:22.0000000
8,9,101,2,3,2025-03-10,2025-03-15,Shipped,3768 Door Way,NaN,2,20,2025-03-10 12:59:04.0000000
9,10,102,3,5,2025-03-15,2025-03-20,Shipped,NaN,NaN,0,60,2025-03-16 23:25:15.0000000

In [10]:
dataset.isnull()

,OrderID,ProductID,CustomerID,SalesPersonID,OrderDate,ShipDate,OrderStatus,ShipAddress,BillAddress,Quantity,Sales,CreationTime
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,True,False,False,False,False

In [56]:
dataset1

,OrderID,ProductID,CustomerID,SalesPersonID,OrderDate,ShipDate,OrderStatus,ShipAddress,BillAddress,Quantity,Sales,CreationTime
0,1,101,2,3,2025-01-01,2025-01-05,Delivered,9833 Mt. Dias Blv.,NaN,1,10,2025-01-01 12:34:56.0000000
1,2,102,3,3,2025-01-05,2025-01-10,Shipped,250 Race Court,NaN,1,15,2025-01-05 23:22:04.0000000
2,3,101,1,5,2025-01-10,2025-01-25,Delivered,8157 W. Book,NaN,2,20,2025-01-10 18:24:08.0000000
3,4,105,1,3,2025-01-20,2025-01-25,Shipped,5724 Victory Lane,NaN,2,60,2025-01-20 05:50:33.0000000
4,5,104,2,5,2025-02-01,2025-02-05,Delivered,NaN,NaN,1,25,2025-02-01 14:02:41.0000000
5,6,104,3,5,2025-02-05,2025-02-10,Delivered,1792 Belmont Rd.,NaN,2,50,2025-02-06 15:34:57.0000000
6,7,102,1,1,2025-02-15,2025-02-27,Delivered,136 Balboa Court,NaN,2,30,2025-02-16 06:22:01.0000000
7,8,101,4,3,2025-02-18,2025-02-27,Shipped,2947 Vine Lane,NaN,3,90,2025-02-18 10:45:22.0000000
8,9,101,2,3,2025-03-10,2025-03-15,Shipped,3768 Door Way,NaN,2,20,2025-03-10 12:59:04.0000000
9,10,102,3,5,2025-03-15,2025-03-20,Shipped,NaN,NaN,0,60,2025-03-16 23:25:15.0000000

## converting data to it's standard format -> yyyy-mm-dd

In [58]:
dataset1["OrderDate"]=pd.to_datetime(dataset1["OrderDate"],errors="coerce")

In [59]:
dataset1

,OrderID,ProductID,CustomerID,SalesPersonID,OrderDate,ShipDate,OrderStatus,ShipAddress,BillAddress,Quantity,Sales,CreationTime
0,1,101,2,3,2025-01-01,2025-01-05,Delivered,9833 Mt. Dias Blv.,NaN,1,10,2025-01-01 12:34:56.0000000
1,2,102,3,3,2025-01-05,2025-01-10,Shipped,250 Race Court,NaN,1,15,2025-01-05 23:22:04.0000000
2,3,101,1,5,2025-01-10,2025-01-25,Delivered,8157 W. Book,NaN,2,20,2025-01-10 18:24:08.0000000
3,4,105,1,3,2025-01-20,2025-01-25,Shipped,5724 Victory Lane,NaN,2,60,2025-01-20 05:50:33.0000000
4,5,104,2,5,2025-02-01,2025-02-05,Delivered,NaN,NaN,1,25,2025-02-01 14:02:41.0000000
5,6,104,3,5,2025-02-05,2025-02-10,Delivered,1792 Belmont Rd.,NaN,2,50,2025-02-06 15:34:57.0000000
6,7,102,1,1,2025-02-15,2025-02-27,Delivered,136 Balboa Court,NaN,2,30,2025-02-16 06:22:01.0000000
7,8,101,4,3,2025-02-18,2025-02-27,Shipped,2947 Vine Lane,NaN,3,90,2025-02-18 10:45:22.0000000
8,9,101,2,3,2025-03-10,2025-03-15,Shipped,3768 Door Way,NaN,2,20,2025-03-10 12:59:04.0000000
9,10,102,3,5,2025-03-15,2025-03-20,Shipped,NaN,NaN,0,60,2025-03-16 23:25:15.0000000

## setting date col as index

In [60]:
dataset1.set_index("OrderDate",inplace=True)

In [61]:
dataset1

,OrderID,ProductID,CustomerID,SalesPersonID,ShipDate,OrderStatus,ShipAddress,BillAddress,Quantity,Sales,CreationTime
OrderDate,,,,,,,,,,,
2025-01-01,1,101,2,3,2025-01-05,Delivered,9833 Mt. Dias Blv.,NaN,1,10,2025-01-01 12:34:56.0000000
2025-01-05,2,102,3,3,2025-01-10,Shipped,250 Race Court,NaN,1,15,2025-01-05 23:22:04.0000000
2025-01-10,3,101,1,5,2025-01-25,Delivered,8157 W. Book,NaN,2,20,2025-01-10 18:24:08.0000000
2025-01-20,4,105,1,3,2025-01-25,Shipped,5724 Victory Lane,NaN,2,60,2025-01-20 05:50:33.0000000
2025-02-01,5,104,2,5,2025-02-05,Delivered,NaN,NaN,1,25,2025-02-01 14:02:41.0000000
2025-02-05,6,104,3,5,2025-02-10,Delivered,1792 Belmont Rd.,NaN,2,50,2025-02-06 15:34:57.0000000
2025-02-15,7,102,1,1,2025-02-27,Delivered,136 Balboa Court,NaN,2,30,2025-02-16 06:22:01.0000000
2025-02-18,8,101,4,3,2025-02-27,Shipped,2947 Vine Lane,NaN,3,90,2025-02-18 10:45:22.0000000
2025-03-10,9,101,2,3,2025-03-15,Shipped,3768 Door Way,NaN,2,20,2025-03-10 12:59:04.0000000
2025-03-15,10,102,3,5,2025-03-20,Shipped,NaN,NaN,0,60,2025-03-16 23:25:15.0000000

## converting string date column "2004-25-04" to pure date column 2004-25-04

In [33]:
pd.to_datetime("2004-10-04")

Timestamp('2004-10-04 00:00:00')

In [62]:
dataset1

,OrderID,ProductID,CustomerID,SalesPersonID,ShipDate,OrderStatus,ShipAddress,BillAddress,Quantity,Sales,CreationTime
OrderDate,,,,,,,,,,,
2025-01-01,1,101,2,3,2025-01-05,Delivered,9833 Mt. Dias Blv.,NaN,1,10,2025-01-01 12:34:56.0000000
2025-01-05,2,102,3,3,2025-01-10,Shipped,250 Race Court,NaN,1,15,2025-01-05 23:22:04.0000000
2025-01-10,3,101,1,5,2025-01-25,Delivered,8157 W. Book,NaN,2,20,2025-01-10 18:24:08.0000000
2025-01-20,4,105,1,3,2025-01-25,Shipped,5724 Victory Lane,NaN,2,60,2025-01-20 05:50:33.0000000
2025-02-01,5,104,2,5,2025-02-05,Delivered,NaN,NaN,1,25,2025-02-01 14:02:41.0000000
2025-02-05,6,104,3,5,2025-02-10,Delivered,1792 Belmont Rd.,NaN,2,50,2025-02-06 15:34:57.0000000
2025-02-15,7,102,1,1,2025-02-27,Delivered,136 Balboa Court,NaN,2,30,2025-02-16 06:22:01.0000000
2025-02-18,8,101,4,3,2025-02-27,Shipped,2947 Vine Lane,NaN,3,90,2025-02-18 10:45:22.0000000
2025-03-10,9,101,2,3,2025-03-15,Shipped,3768 Door Way,NaN,2,20,2025-03-10 12:59:04.0000000
2025-03-15,10,102,3,5,2025-03-20,Shipped,NaN,NaN,0,60,2025-03-16 23:25:15.0000000

## Weekly Resampling

In [79]:
dataset1.resample("W").sum()

,OrderID,ProductID,CustomerID,SalesPersonID,ShipDate,OrderStatus,ShipAddress,BillAddress,Quantity,Sales,CreationTime
OrderDate,,,,,,,,,,,
2025-01-05,3,203,5,6,2025-01-052025-01-10,DeliveredShipped,9833 Mt. Dias Blv.250 Race Court,0,2,25,2025-01-01 12:34:56.00000002025-01-05 23:22:04...
2025-01-12,3,101,1,5,2025-01-25,Delivered,8157 W. Book,0,2,20,2025-01-10 18:24:08.0000000
2025-01-19,0,0,0,0,0,0,0,0,0,0,0
2025-01-26,4,105,1,3,2025-01-25,Shipped,5724 Victory Lane,0,2,60,2025-01-20 05:50:33.0000000
2025-02-02,5,104,2,5,2025-02-05,Delivered,0,0,1,25,2025-02-01 14:02:41.0000000
2025-02-09,6,104,3,5,2025-02-10,Delivered,1792 Belmont Rd.,0,2,50,2025-02-06 15:34:57.0000000
2025-02-16,7,102,1,1,2025-02-27,Delivered,136 Balboa Court,0,2,30,2025-02-16 06:22:01.0000000
2025-02-23,8,101,4,3,2025-02-27,Shipped,2947 Vine Lane,0,3,90,2025-02-18 10:45:22.0000000
2025-03-02,0,0,0,0,0,0,0,0,0,0,0
2025-03-09,0,0,0,0,0,0,0,0,0,0,0
2025-03-16,19,203,5,8,2025-03-152025-03-20,ShippedShipped,3768 Door Way,0,2,80,2025-03-10 12:59:04.00000002025-03-16 23:25:15...

### index also has data type

In [66]:
dataset1.index.dtype

dtype('<M8[ns]')

## Month end resampling

In [68]:
dataset1.resample("ME").sum()

,OrderID,ProductID,CustomerID,SalesPersonID,ShipDate,OrderStatus,ShipAddress,BillAddress,Quantity,Sales,CreationTime
OrderDate,,,,,,,,,,,
2025-01-31,10,409,7,14,2025-01-052025-01-102025-01-252025-01-25,DeliveredShippedDeliveredShipped,9833 Mt. Dias Blv.250 Race Court8157 W. Book57...,0,6,105,2025-01-01 12:34:56.00000002025-01-05 23:22:04...
2025-02-28,26,411,10,14,2025-02-052025-02-102025-02-272025-02-27,DeliveredDeliveredDeliveredShipped,1792 Belmont Rd.136 Balboa Court2947 Vine Lane,0,8,195,2025-02-01 14:02:41.00000002025-02-06 15:34:57...
2025-03-31,19,203,5,8,2025-03-152025-03-20,ShippedShipped,3768 Door Way,0,2,80,2025-03-10 12:59:04.00000002025-03-16 23:25:15...

## Month start resampling

In [70]:
dataset1.resample("MS").sum()

,OrderID,ProductID,CustomerID,SalesPersonID,ShipDate,OrderStatus,ShipAddress,BillAddress,Quantity,Sales,CreationTime
OrderDate,,,,,,,,,,,
2025-01-01,10,409,7,14,2025-01-052025-01-102025-01-252025-01-25,DeliveredShippedDeliveredShipped,9833 Mt. Dias Blv.250 Race Court8157 W. Book57...,0,6,105,2025-01-01 12:34:56.00000002025-01-05 23:22:04...
2025-02-01,26,411,10,14,2025-02-052025-02-102025-02-272025-02-27,DeliveredDeliveredDeliveredShipped,1792 Belmont Rd.136 Balboa Court2947 Vine Lane,0,8,195,2025-02-01 14:02:41.00000002025-02-06 15:34:57...
2025-03-01,19,203,5,8,2025-03-152025-03-20,ShippedShipped,3768 Door Way,0,2,80,2025-03-10 12:59:04.00000002025-03-16 23:25:15...

## Annually(resamping)

In [72]:
dataset1.resample("YE").sum()

,OrderID,ProductID,CustomerID,SalesPersonID,ShipDate,OrderStatus,ShipAddress,BillAddress,Quantity,Sales,CreationTime
OrderDate,,,,,,,,,,,
2025-12-31,55,1023,22,36,2025-01-052025-01-102025-01-252025-01-252025-0...,DeliveredShippedDeliveredShippedDeliveredDeliv...,9833 Mt. Dias Blv.250 Race Court8157 W. Book57...,0,16,380,2025-01-01 12:34:56.00000002025-01-05 23:22:04...

In [74]:
dataset1.resample("YS").sum()

,OrderID,ProductID,CustomerID,SalesPersonID,ShipDate,OrderStatus,ShipAddress,BillAddress,Quantity,Sales,CreationTime
OrderDate,,,,,,,,,,,
2025-01-01,55,1023,22,36,2025-01-052025-01-102025-01-252025-01-252025-0...,DeliveredShippedDeliveredShippedDeliveredDeliv...,9833 Mt. Dias Blv.250 Race Court8157 W. Book57...,0,16,380,2025-01-01 12:34:56.00000002025-01-05 23:22:04...

# Let's try to understand sales trend what happened it increased or decreased

## Step-1 > finding sales column

In [80]:
dataset1.columns

Index(['OrderID', 'ProductID', 'CustomerID', 'SalesPersonID', 'ShipDate',
       'OrderStatus', 'ShipAddress', 'BillAddress', 'Quantity', 'Sales',
       'CreationTime'],
      dtype='object')

## shifting

In [82]:
dataset1["shift_by_1"]=dataset1["Sales"].shift(1)

In [83]:
dataset1

,OrderID,ProductID,CustomerID,SalesPersonID,ShipDate,OrderStatus,ShipAddress,BillAddress,Quantity,Sales,CreationTime,shift_by_1
OrderDate,,,,,,,,,,,,
2025-01-01,1,101,2,3,2025-01-05,Delivered,9833 Mt. Dias Blv.,NaN,1,10,2025-01-01 12:34:56.0000000,NaN
2025-01-05,2,102,3,3,2025-01-10,Shipped,250 Race Court,NaN,1,15,2025-01-05 23:22:04.0000000,10.0
2025-01-10,3,101,1,5,2025-01-25,Delivered,8157 W. Book,NaN,2,20,2025-01-10 18:24:08.0000000,15.0
2025-01-20,4,105,1,3,2025-01-25,Shipped,5724 Victory Lane,NaN,2,60,2025-01-20 05:50:33.0000000,20.0
2025-02-01,5,104,2,5,2025-02-05,Delivered,NaN,NaN,1,25,2025-02-01 14:02:41.0000000,60.0
2025-02-05,6,104,3,5,2025-02-10,Delivered,1792 Belmont Rd.,NaN,2,50,2025-02-06 15:34:57.0000000,25.0
2025-02-15,7,102,1,1,2025-02-27,Delivered,136 Balboa Court,NaN,2,30,2025-02-16 06:22:01.0000000,50.0
2025-02-18,8,101,4,3,2025-02-27,Shipped,2947 Vine Lane,NaN,3,90,2025-02-18 10:45:22.0000000,30.0
2025-03-10,9,101,2,3,2025-03-15,Shipped,3768 Door Way,NaN,2,20,2025-03-10 12:59:04.0000000,90.0
2025-03-15,10,102,3,5,2025-03-20,Shipped,NaN,NaN,0,60,2025-03-16 23:25:15.0000000,20.0

### now afrer shift we got nan in shift column - so let's fill 0

In [84]:
dataset1["shift_by_1"].isnull()

OrderDate
2025-01-01     True
2025-01-05    False
2025-01-10    False
2025-01-20    False
2025-02-01    False
2025-02-05    False
2025-02-15    False
2025-02-18    False
2025-03-10    False
2025-03-15    False
Name: shift_by_1, dtype: bool

In [96]:
dataset1["shift_by_1"].fillna(0,inplace=True)

C:\Users\91790\AppData\Local\Temp\ipykernel_7828\103234687.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset1["shift_by_1"].fillna(0,inplace=True)

## calculating change (kl se aaj tk me kitna chnage hua)

In [97]:
dataset1["sales_change"]=dataset1["Sales"]-dataset1["shift_by_1"]

In [98]:
dataset1

,OrderID,ProductID,CustomerID,SalesPersonID,ShipDate,OrderStatus,ShipAddress,BillAddress,Quantity,Sales,CreationTime,shift_by_1,sales_change
OrderDate,,,,,,,,,,,,,
2025-01-01,1,101,2,3,2025-01-05,Delivered,9833 Mt. Dias Blv.,0,1,10,2025-01-01 12:34:56.0000000,0.0,10.0
2025-01-05,2,102,3,3,2025-01-10,Shipped,250 Race Court,0,1,15,2025-01-05 23:22:04.0000000,10.0,5.0
2025-01-10,3,101,1,5,2025-01-25,Delivered,8157 W. Book,0,2,20,2025-01-10 18:24:08.0000000,15.0,5.0
2025-01-20,4,105,1,3,2025-01-25,Shipped,5724 Victory Lane,0,2,60,2025-01-20 05:50:33.0000000,20.0,40.0
2025-02-01,5,104,2,5,2025-02-05,Delivered,0,0,1,25,2025-02-01 14:02:41.0000000,60.0,-35.0
2025-02-05,6,104,3,5,2025-02-10,Delivered,1792 Belmont Rd.,0,2,50,2025-02-06 15:34:57.0000000,25.0,25.0
2025-02-15,7,102,1,1,2025-02-27,Delivered,136 Balboa Court,0,2,30,2025-02-16 06:22:01.0000000,50.0,-20.0
2025-02-18,8,101,4,3,2025-02-27,Shipped,2947 Vine Lane,0,3,90,2025-02-18 10:45:22.0000000,30.0,60.0
2025-03-10,9,101,2,3,2025-03-15,Shipped,3768 Door Way,0,2,20,2025-03-10 12:59:04.0000000,90.0,-70.0
2025-03-15,10,102,3,5,2025-03-20,Shipped,0,0,0,60,2025-03-16 23:25:15.0000000,20.0,40.0

## now for better understanding marking it with up and down

In [100]:
dataset1["sales_up_or_down"]=dataset1["sales_change"].apply(lambda x:"up" if x>0 else "down")

In [101]:
dataset1

,OrderID,ProductID,CustomerID,SalesPersonID,ShipDate,OrderStatus,ShipAddress,BillAddress,Quantity,Sales,CreationTime,shift_by_1,sales_change,sales_up_or_down
OrderDate,,,,,,,,,,,,,,
2025-01-01,1,101,2,3,2025-01-05,Delivered,9833 Mt. Dias Blv.,0,1,10,2025-01-01 12:34:56.0000000,0.0,10.0,up
2025-01-05,2,102,3,3,2025-01-10,Shipped,250 Race Court,0,1,15,2025-01-05 23:22:04.0000000,10.0,5.0,up
2025-01-10,3,101,1,5,2025-01-25,Delivered,8157 W. Book,0,2,20,2025-01-10 18:24:08.0000000,15.0,5.0,up
2025-01-20,4,105,1,3,2025-01-25,Shipped,5724 Victory Lane,0,2,60,2025-01-20 05:50:33.0000000,20.0,40.0,up
2025-02-01,5,104,2,5,2025-02-05,Delivered,0,0,1,25,2025-02-01 14:02:41.0000000,60.0,-35.0,down
2025-02-05,6,104,3,5,2025-02-10,Delivered,1792 Belmont Rd.,0,2,50,2025-02-06 15:34:57.0000000,25.0,25.0,up
2025-02-15,7,102,1,1,2025-02-27,Delivered,136 Balboa Court,0,2,30,2025-02-16 06:22:01.0000000,50.0,-20.0,down
2025-02-18,8,101,4,3,2025-02-27,Shipped,2947 Vine Lane,0,3,90,2025-02-18 10:45:22.0000000,30.0,60.0,up
2025-03-10,9,101,2,3,2025-03-15,Shipped,3768 Door Way,0,2,20,2025-03-10 12:59:04.0000000,90.0,-70.0,down
2025-03-15,10,102,3,5,2025-03-20,Shipped,0,0,0,60,2025-03-16 23:25:15.0000000,20.0,40.0,up

In [105]:
dataset1[["Sales","sales_change","sales_up_or_down"]]

            Sales  sales_change sales_up_or_down
OrderDate
2025-01-01     10          10.0               up
2025-01-05     15           5.0               up
2025-01-10     20           5.0               up
2025-01-20     60          40.0               up
2025-02-01     25         -35.0             down
2025-02-05     50          25.0               up
2025-02-15     30         -20.0             down
2025-02-18     90          60.0               up
2025-03-10     20         -70.0             down
2025-03-15     60          40.0               up

## Rolling Calculation

In [107]:
dataset1["rolling_calculated_sales"]=dataset1["Sales"].rolling(window=2).mean()

In [108]:
dataset1

,OrderID,ProductID,CustomerID,SalesPersonID,ShipDate,OrderStatus,ShipAddress,BillAddress,Quantity,Sales,CreationTime,shift_by_1,sales_change,sales_up_or_down,rolling_calculated_sales
OrderDate,,,,,,,,,,,,,,,
2025-01-01,1,101,2,3,2025-01-05,Delivered,9833 Mt. Dias Blv.,0,1,10,2025-01-01 12:34:56.0000000,0.0,10.0,up,NaN
2025-01-05,2,102,3,3,2025-01-10,Shipped,250 Race Court,0,1,15,2025-01-05 23:22:04.0000000,10.0,5.0,up,12.5
2025-01-10,3,101,1,5,2025-01-25,Delivered,8157 W. Book,0,2,20,2025-01-10 18:24:08.0000000,15.0,5.0,up,17.5
2025-01-20,4,105,1,3,2025-01-25,Shipped,5724 Victory Lane,0,2,60,2025-01-20 05:50:33.0000000,20.0,40.0,up,40.0
2025-02-01,5,104,2,5,2025-02-05,Delivered,0,0,1,25,2025-02-01 14:02:41.0000000,60.0,-35.0,down,42.5
2025-02-05,6,104,3,5,2025-02-10,Delivered,1792 Belmont Rd.,0,2,50,2025-02-06 15:34:57.0000000,25.0,25.0,up,37.5
2025-02-15,7,102,1,1,2025-02-27,Delivered,136 Balboa Court,0,2,30,2025-02-16 06:22:01.0000000,50.0,-20.0,down,40.0
2025-02-18,8,101,4,3,2025-02-27,Shipped,2947 Vine Lane,0,3,90,2025-02-18 10:45:22.0000000,30.0,60.0,up,60.0
2025-03-10,9,101,2,3,2025-03-15,Shipped,3768 Door Way,0,2,20,2025-03-10 12:59:04.0000000,90.0,-70.0,down,55.0
2025-03-15,10,102,3,5,2025-03-20,Shipped,0,0,0,60,2025-03-16 23:25:15.0000000,20.0,40.0,up,40.0

# FOR TREND ANALYSIS->
- df["datecol"]=pd.datetime(df["datecol"])
- df.set_index("datecol")
- df["numerical_col"].shift(n)
- difference calc b/w original cola nd shifted col
-  apply lambda

- resampling

- rolling calc