# PANDAS

### reading csv file -> retuen DataFrame

In [3]:
import pandas as pd

dataset_df = pd.read_csv("italy-covid-daywise .csv")          # pandas file read krke dataframe deta hai (dataframe is panda's core DS to store 
                                                                         #  and work with tabular data
dataset_df

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

### type() function

type(dataset_df)

In [4]:
#  dekho d`ataframe ek frame hai aur frame mtlb something rectangular ya fir sq i.e tabular with some row and col

### .info()

In [5]:
dataset_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        248 non-null    object
 1   new_cases   248 non-null    float64
 2   new_deaths  248 non-null    float64
 3   new_tests   135 non-null    float64
dtypes: float64(3), object(1)
memory usage: 7.9+ KB

In [6]:
# object -> general datatype -> reurned when it could not fighure out the exact datatype of a particular columun

### .describe()

In [7]:
dataset_df.describe()

         new_cases  new_deaths     new_tests
count   248.000000  248.000000    135.000000
mean   1094.818548  143.133065  31699.674074
std    1554.508002  227.105538  11622.209757
min    -148.000000  -31.000000   7841.000000
25%     123.000000    3.000000  25259.000000
50%     342.000000   17.000000  29545.000000
75%    1371.750000  175.250000  37711.000000
max    6557.000000  971.000000  95273.000000

### .columns

In [8]:
dataset_df.columns

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='object')

### .shape

In [9]:
dataset_df.shape

(248, 4)

In [10]:
### DataFrame of pandas is similar to dictionary of lists

In [11]:
# internally
#  dataset = {
#            'col1' : [val1 , val2 , --],
#            'col2' : [val1 , val2 , --]
#            }

### accesing values of a column in a dataset (DataFrame)

In [12]:
dataset_df['new_cases']

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
        ...
243    1444.0
244    1365.0
245     996.0
246     975.0
247    1326.0
Name: new_cases, Length: 248, dtype: float64

###  accessign ele using indexing

In [13]:
# syntax      dataset_df[colname][idx]

In [14]:
dataset_df["new_cases"][246]

np.float64(975.0)

In [15]:
dataset_df["new_cases"][200]

np.float64(231.0)

### acessing ele using    .at

In [16]:
# syntax - >    dataset_df.at(rowno. , 'colname')

In [17]:
dataset_df.at[246 , "new_cases"]

np.float64(975.0)

### dataset_df['colname'] -> similar to -> dataset_df.colname

In [18]:
dataset_df.new_cases

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
        ...
243    1444.0
244    1365.0
245     996.0
246     975.0
247    1326.0
Name: new_cases, Length: 248, dtype: float64

### to access multiple columns -> u can pass list of columns

In [19]:
# let's know what column are there in our data
dataset_df.columns

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='object')

In [20]:
# now accessing multiple columns
dataset_df[["new_cases" , "new_deaths","new_tests"]]

     new_cases  new_deaths  new_tests
0          0.0         0.0        NaN
1          0.0         0.0        NaN
2          0.0         0.0        NaN
3          0.0         0.0        NaN
4          0.0         0.0        NaN
..         ...         ...        ...
243     1444.0         1.0    53541.0
244     1365.0         4.0    42583.0
245      996.0         6.0    54395.0
246      975.0         8.0        NaN
247     1326.0         6.0        NaN

[248 rows x 3 columns]

### making changes in subset of DataFrame reflects changes in original DataFrame -> bcz both points to same DataFrame

###  .copy() function ->  making copy of a complete DataFrame

In [21]:
dataset_df_copy = dataset_df.copy()

In [22]:
dataset_df_copy

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

### to acces row of a DataFrame

In [23]:
dataset_df_row = dataset_df.loc[5]
dataset_df_row

date          2020-01-05
new_cases            0.0
new_deaths           0.0
new_tests            NaN
Name: 5, dtype: object

### to view first few or last few rows of DataFrame

### .head(no. of rows) function

In [24]:
dataset_df.head(5)

         date  new_cases  new_deaths  new_tests
0  2019-12-31        0.0         0.0        NaN
1  2020-01-01        0.0         0.0        NaN
2  2020-01-02        0.0         0.0        NaN
3  2020-01-03        0.0         0.0        NaN
4  2020-01-04        0.0         0.0        NaN

### .tail (no. of rows) function

In [25]:
dataset_df.tail(5)

           date  new_cases  new_deaths  new_tests
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

### 0(zero)  v/s  NaN
 0 -> its 0 value   and 
             NaN -> no information povides i.e not a number but type comes to be float

In [26]:
dataset_df.at[0,"new_cases"]

np.float64(0.0)

In [27]:
type(dataset_df.at[0,"new_cases"])

numpy.float64

In [28]:
dataset_df.at[0,"new_tests"]

np.float64(nan)

In [29]:
type(dataset_df.at[0,"new_tests"])

numpy.float64

### .first_valid_index() function -> to know from where does first valid value other than NaN starts in a column

### syntax -> dataset_df.colname.fisrt_valid_index()

In [30]:
dataset_df.new_tests.first_valid_index()

111

In [31]:
dataset_df.new_cases.first_valid_index()

0

In [32]:
dataset_df.loc[6]

date          2020-01-06
new_cases            0.0
new_deaths           0.0
new_tests            NaN
Name: 6, dtype: object

### .loc[start_idx : end_idx(included)] ->  accessing range of rows

In [33]:
dataset_df.loc[108:117]

           date  new_cases  new_deaths  new_tests
108  2020-04-17     3786.0       525.0        NaN
109  2020-04-18     3493.0       575.0        NaN
110  2020-04-19     3491.0       480.0        NaN
111  2020-04-20     3047.0       433.0     7841.0
112  2020-04-21     2256.0       454.0    28095.0
113  2020-04-22     2729.0       534.0    44248.0
114  2020-04-23     3370.0       437.0    37083.0
115  2020-04-24     2646.0       464.0    95273.0
116  2020-04-25     3021.0       420.0    38676.0
117  2020-04-26     2357.0       415.0    24113.0

### .sample(no. of samples -> gives random rows )  -> used to retrieve random sample of rows from the DataFrame

In [34]:
dataset_df.sample(10)

           date  new_cases  new_deaths  new_tests
67   2020-03-07      778.0        49.0        NaN
13   2020-01-13        0.0         0.0        NaN
73   2020-03-13     2651.0       189.0        NaN
177  2020-06-25      577.0       -31.0    29421.0
2    2020-01-02        0.0         0.0        NaN
205  2020-07-23      280.0         9.0    33018.0
200  2020-07-18      231.0        11.0    27569.0
152  2020-05-31      416.0       111.0    28948.0
116  2020-04-25     3021.0       420.0    38676.0
21   2020-01-21        0.0         0.0        NaN

## REVISION TILL NOW

In [35]:
# DataFrame -> core data structure hai pandas ka
# that helps to store and work with tabular data
# import stat
# pd.read_csv
# type () function
# .info()  -> class , range idx , data col - name , no. of non null , data type , memory usage
# .describe() -> stats deta hai like count , std, mean ,max , min etc
# .columns() -> sare col ke names retrieve krta hai
# .shape -> ((no. of row , no of col)
# accessing values of a col ->   _[colname]  <- series
# aceesing value/ele at specific index ->  _[colname][idx]
# same using .at ->  _.at[idx/row no , "colname"]
# aceesing multiple col or subset of DataFrame->  _[[col1,col2,col3--]]   <- we pass list of columns
# making copy of dataframe ->   _.copy()
# accessign complete row at specific idx->  _.loc[idx]
# to view first few or last few row -> _.head(no of rows) , _.tail(no of rows)
# 0.0 V/S NaN
# to know from where valid value starts other than NaN -> _.colnaem.first_valid_index()
# accessing range of rows -> _.loc[start_idx : end_idx]    <- end idx included
# to get random sample of rows from dataframe  ->  _.sample(no. of samples u need)

# to deal with row -> we use .loc[idx]

## Analyzing data from dataframes

In [36]:
## let's answer some questions about our data

In [37]:
import pandas as pd

dataset_df = pd.read_csv ("italy-covid-daywise .csv")
dataset_df

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

In [38]:
# Q1. What is the total number of reported cases and deaths related to covid-19 in italy ?

In [39]:

what_col_we_have = dataset_df.columns
what_col_we_have

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='object')

In [40]:
reported_cases = dataset_df.new_cases.sum()
reported_cases

np.float64(271515.0)

In [41]:
reported_deaths = dataset_df.new_deaths.sum()                 #  -> .sum()  ignores NaN
reported_deaths

np.float64(35497.0)

In [42]:
print("the number of reported cases are {} and of reported deaths are {}".format(reported_cases,reported_deaths.))

SyntaxError: invalid syntax (3431442391.py, line 1)

In [43]:
# Q2. What is the overall death ratio ( ratio of reported deaths to reported cases )

In [44]:
death_rate = dataset_df.new_deaths.sum() / dataset_df.new_cases.sum()
death_rate

np.float64(0.13073679170579894)

In [45]:
print( "The overall death ratio is {:.2f} % .".format(death_rate))         # to format decimal we use {:.2f} in print statement

The overall death ratio is 0.13 % .

In [46]:
# Q3. What is the overall number of tests conducted? A total of 935310 tests were conducted before daily test numbers were reported.

In [47]:
# ques ka mtlb itne no. of test conduct ho ja rhe the report hone se pehel hi
# therefore overall no. of test hua = jitne conduct hue + jitne report hue

In [48]:
no_of_test_conducted_before_reporting = 935310
no_of_tests_reported = dataset_df.new_tests.sum()
no_of_tests_reported

np.float64(4279456.0)

In [49]:
total_overall_tests_conducted = no_of_test_conducted_before_reporting + no_of_tests_reported
total_overall_tests_conducted

np.float64(5214766.0)

In [50]:
print("Total overall tests condcuted are {}.".format(total_overall_tests_conducted))

Total overall tests condcuted are 5214766.0.

In [51]:
# Q3. What fraction of tests resturned a positive result

In [52]:
what_col_we_have = dataset_df.columns
what_col_we_have

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='object')

In [53]:
positive_results = reported_cases/ total_overall_tests_conducted
positive_results

np.float64(0.05206657403227681)

In [54]:
print("The total no. of positive results are {:.2f}.".format(positive_results))

The total no. of positive results are 0.05.

# Querying and Sorting rows

In [55]:
# using boolean expressions -> that returns series containing True and False

In [56]:
# days that have more than 1000 reported cases.

day_when_more_than1000_cases_reported = dataset_df.new_cases > 1000

day_when_more_than1000_cases_reported

0      False
1      False
2      False
3      False
4      False
       ...
243     True
244     True
245    False
246    False
247     True
Name: new_cases, Length: 248, dtype: bool

In [57]:
dataset_df[day_when_more_than1000_cases_reported ]        # passing True False Series in dataset_df[here] -> we get only rows with
                                                            # True values naaad the rows with False values are skipped

           date  new_cases  new_deaths  new_tests
68   2020-03-08     1247.0        36.0        NaN
69   2020-03-09     1492.0       133.0        NaN
70   2020-03-10     1797.0        98.0        NaN
72   2020-03-12     2313.0       196.0        NaN
73   2020-03-13     2651.0       189.0        NaN
..          ...        ...         ...        ...
241  2020-08-28     1409.0         5.0    65135.0
242  2020-08-29     1460.0         9.0    64294.0
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
247  2020-09-03     1326.0         6.0        NaN

[72 rows x 4 columns]

In [58]:
day_when_more_than1000_cases_reported = dataset_df[dataset_df.new_cases>1000]       # bade dataframe me se wo subset of dataframe do jha values True hai
day_when_more_than1000_cases_reported

           date  new_cases  new_deaths  new_tests
68   2020-03-08     1247.0        36.0        NaN
69   2020-03-09     1492.0       133.0        NaN
70   2020-03-10     1797.0        98.0        NaN
72   2020-03-12     2313.0       196.0        NaN
73   2020-03-13     2651.0       189.0        NaN
..          ...        ...         ...        ...
241  2020-08-28     1409.0         5.0    65135.0
242  2020-08-29     1460.0         9.0    64294.0
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
247  2020-09-03     1326.0         6.0        NaN

[72 rows x 4 columns]

### in jupyter we get to see only first 5 and last 5 rows when we retreieve large amout of data, so to get full data

In [59]:
import pandas as pd
from IPython.display import display                                                    # to see all rows of data
with pd.option_context("display.max_rows",100):
    display(dataset_df[dataset_df.new_cases>1000])

           date  new_cases  new_deaths  new_tests
68   2020-03-08     1247.0        36.0        NaN
69   2020-03-09     1492.0       133.0        NaN
70   2020-03-10     1797.0        98.0        NaN
72   2020-03-12     2313.0       196.0        NaN
73   2020-03-13     2651.0       189.0        NaN
74   2020-03-14     2547.0       252.0        NaN
75   2020-03-15     3497.0       173.0        NaN
76   2020-03-16     2823.0       370.0        NaN
77   2020-03-17     4000.0       347.0        NaN
78   2020-03-18     3526.0       347.0        NaN
79   2020-03-19     4207.0       473.0        NaN
80   2020-03-20     5322.0       429.0        NaN
81   2020-03-21     5986.0       625.0        NaN
82   2020-03-22     6557.0       795.0        NaN
83   2020-03-23     5560.0       649.0        NaN
84   2020-03-24     4789.0       601.0        NaN
85   2020-03-25     5249.0       743.0        NaN
86   2020-03-26     5210.0       685.0        NaN
87   2020-03-27     6153.0       660.0        NaN
88   2020-03-28     5959.0       971.0        NaN
89   2020-03-29     5974.0       887.0        NaN
90   2020-03-30     5217.0       758.0        NaN
91   2020-03-31     4050.0       810.0        NaN
92   2020-04-01     4053.0       839.0        NaN
93   2020-04-02     4782.0       727.0        NaN
94   2020-04-03     4668.0       760.0        NaN
95   2020-04-04     4585.0       764.0        NaN
96   2020-04-05     4805.0       681.0        NaN
97   2020-04-06     4316.0       527.0        NaN
98   2020-04-07     3599.0       636.0        NaN
99   2020-04-08     3039.0       604.0        NaN
100  2020-04-09     3836.0       540.0        NaN
101  2020-04-10     4204.0       612.0        NaN
102  2020-04-11     3951.0       570.0        NaN
103  2020-04-12     4694.0       619.0        NaN
104  2020-04-13     4092.0       431.0        NaN
105  2020-04-14     3153.0       564.0        NaN
106  2020-04-15     2972.0       604.0        NaN
107  2020-04-16     2667.0       578.0        NaN
108  2020-04-17     3786.0       525.0        NaN
109  2020-04-18     3493.0       575.0        NaN
110  2020-04-19     3491.0       480.0        NaN
111  2020-04-20     3047.0       433.0     7841.0
112  2020-04-21     2256.0       454.0    28095.0
113  2020-04-22     2729.0       534.0    44248.0
114  2020-04-23     3370.0       437.0    37083.0
115  2020-04-24     2646.0       464.0    95273.0
116  2020-04-25     3021.0       420.0    38676.0
117  2020-04-26     2357.0       415.0    24113.0
118  2020-04-27     2324.0       260.0    26678.0
119  2020-04-28     1739.0       333.0    37554.0
120  2020-04-29     2091.0       382.0    38589.0
121  2020-04-30     2086.0       323.0    41441.0
122  2020-05-01     1872.0       285.0    43732.0
123  2020-05-02     1965.0       269.0    31231.0
124  2020-05-03     1900.0       474.0    27047.0
125  2020-05-04     1389.0       174.0    22999.0
126  2020-05-05     1221.0       195.0    32211.0
127  2020-05-06     1075.0       236.0    37771.0
128  2020-05-07     1444.0       369.0    13665.0
129  2020-05-08     1401.0       274.0    45428.0
130  2020-05-09     1327.0       243.0    36091.0
131  2020-05-10     1083.0       194.0    31384.0
134  2020-05-13     1402.0       172.0    37049.0
236  2020-08-23     1071.0         3.0    47463.0
237  2020-08-24     1209.0         7.0    33358.0
240  2020-08-27     1366.0        13.0    57640.0
241  2020-08-28     1409.0         5.0    65135.0
242  2020-08-29     1460.0         9.0    64294.0
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
247  2020-09-03     1326.0         6.0        NaN

In [60]:
positive_results

np.float64(0.05206657403227681)

### to determine days when ratio of cases reported to tests conducted is higher than overall positive rasults

In [61]:
higher_than_pos_res=dataset_df[(dataset_df.new_cases /  dataset_df.new_tests ) > positive_results]  # when ratio of cses to test was > than positive results

In [62]:
higher_than_pos_res

           date  new_cases  new_deaths  new_tests
111  2020-04-20     3047.0       433.0     7841.0
112  2020-04-21     2256.0       454.0    28095.0
113  2020-04-22     2729.0       534.0    44248.0
114  2020-04-23     3370.0       437.0    37083.0
116  2020-04-25     3021.0       420.0    38676.0
117  2020-04-26     2357.0       415.0    24113.0
118  2020-04-27     2324.0       260.0    26678.0
120  2020-04-29     2091.0       382.0    38589.0
123  2020-05-02     1965.0       269.0    31231.0
124  2020-05-03     1900.0       474.0    27047.0
125  2020-05-04     1389.0       174.0    22999.0
128  2020-05-07     1444.0       369.0    13665.0

### even we can add new col for this ratio of cases to tests

In [63]:
dataset_df["positive_rate"] = dataset_df.new_cases / dataset_df.new_tests

In [64]:
dataset_df

           date  new_cases  new_deaths  new_tests  positive_rate
0    2019-12-31        0.0         0.0        NaN            NaN
1    2020-01-01        0.0         0.0        NaN            NaN
2    2020-01-02        0.0         0.0        NaN            NaN
3    2020-01-03        0.0         0.0        NaN            NaN
4    2020-01-04        0.0         0.0        NaN            NaN
..          ...        ...         ...        ...            ...
243  2020-08-30     1444.0         1.0    53541.0       0.026970
244  2020-08-31     1365.0         4.0    42583.0       0.032055
245  2020-09-01      996.0         6.0    54395.0       0.018311
246  2020-09-02      975.0         8.0        NaN            NaN
247  2020-09-03     1326.0         6.0        NaN            NaN

[248 rows x 5 columns]

### removing positive rate column ( inplace = True -> change in original DF , inplace = False -> gives new DF and original remains untouched ) , always pass col name in list form

In [65]:
dataset_df.drop(columns=["positive_rate"],inplace=True)

In [66]:
dataset_df

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

# Sorting rows using column values

### to get in ascending (low to high)-> ascending=True ; for descending(high to low) -> ascending=False ; head(n)-> to tell how many rows we want from top

In [67]:
# finding days with highest no. of cases

dataset_df.sort_values("new_deaths",ascending=False).head(10)

          date  new_cases  new_deaths  new_tests
88  2020-03-28     5959.0       971.0        NaN
89  2020-03-29     5974.0       887.0        NaN
92  2020-04-01     4053.0       839.0        NaN
91  2020-03-31     4050.0       810.0        NaN
82  2020-03-22     6557.0       795.0        NaN
95  2020-04-04     4585.0       764.0        NaN
94  2020-04-03     4668.0       760.0        NaN
90  2020-03-30     5217.0       758.0        NaN
85  2020-03-25     5249.0       743.0        NaN
93  2020-04-02     4782.0       727.0        NaN

In [68]:
# to sort new cases in ascending order

In [69]:
dataset_df.sort_values("new_cases",ascending=True).head(10)

           date  new_cases  new_deaths  new_tests
172  2020-06-20     -148.0        47.0    29875.0
0    2019-12-31        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
5    2020-01-05        0.0         0.0        NaN
6    2020-01-06        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
8    2020-01-08        0.0         0.0        NaN
9    2020-01-09        0.0         0.0        NaN

In [70]:
dataset_df.loc[169:175]

           date  new_cases  new_deaths  new_tests
169  2020-06-17      210.0        34.0    33957.0
170  2020-06-18      328.0        43.0    32921.0
171  2020-06-19      331.0        66.0    28570.0
172  2020-06-20     -148.0        47.0    29875.0
173  2020-06-21      264.0        49.0    24581.0
174  2020-06-22      224.0        24.0    16152.0
175  2020-06-23      221.0        23.0    23225.0

## dealing with missing or faulty values
- replace it with 0
- replace it with avg of the entire col
- replace it with avg of it's prev and next val
- discard that row entirely

### .at method is used to modify data within a DataFrame

In [71]:
# first we look at column

dataset_df.new_cases

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
        ...
243    1444.0
244    1365.0
245     996.0
246     975.0
247    1326.0
Name: new_cases, Length: 248, dtype: float64

In [72]:
# now we modify using .at

dataset_df.at[172,"new_cases"] = ( (dataset_df.at[171,"new_cases"]) + (dataset_df.at[172,"new_cases"] )) / 2

In [73]:
dataset_df.at[172,"new_cases"]

np.float64(91.5)

## taking sum of values in a column

In [74]:
dataset_df["new_cases"].sum()

np.float64(271754.5)

# working with timeline factors

In [75]:
dataset_df["date"]

0      2019-12-31
1      2020-01-01
2      2020-01-02
3      2020-01-03
4      2020-01-04
          ...
243    2020-08-30
244    2020-08-31
245    2020-09-01
246    2020-09-02
247    2020-09-03
Name: date, Length: 248, dtype: object

In [76]:
type(dataset_df["date"])

pandas.core.series.Series

### converting time/date col of series into datetime format

In [77]:
dataset_df["date"] = pd.to_datetime(dataset_df["date"])      # before this individual col dtype was object
                                                              # after -> datetime

In [78]:
dataset_df["date"]

0     2019-12-31
1     2020-01-01
2     2020-01-02
3     2020-01-03
4     2020-01-04
         ...
243   2020-08-30
244   2020-08-31
245   2020-09-01
246   2020-09-02
247   2020-09-03
Name: date, Length: 248, dtype: datetime64[ns]

In [79]:
type(dataset_df["date"])

pandas.core.series.Series

### now we can extract different parts of datetime using DatetimeIndex class -> .year , .month ,.day , .weekday

In [80]:
dataset_df["year"] = pd.DatetimeIndex(dataset_df["date"]).year

In [81]:
dataset_df["month"] = pd.DatetimeIndex(dataset_df["date"]).month

In [82]:
dataset_df["day"] = pd.DatetimeIndex(dataset_df["date"]).day

In [83]:
dataset_df["week"] = pd.DatetimeIndex(dataset_df["date"]).weekday

In [84]:
dataset_df

          date  new_cases  new_deaths  new_tests  year  month  day  week
0   2019-12-31        0.0         0.0        NaN  2019     12   31     1
1   2020-01-01        0.0         0.0        NaN  2020      1    1     2
2   2020-01-02        0.0         0.0        NaN  2020      1    2     3
3   2020-01-03        0.0         0.0        NaN  2020      1    3     4
4   2020-01-04        0.0         0.0        NaN  2020      1    4     5
..         ...        ...         ...        ...   ...    ...  ...   ...
243 2020-08-30     1444.0         1.0    53541.0  2020      8   30     6
244 2020-08-31     1365.0         4.0    42583.0  2020      8   31     0
245 2020-09-01      996.0         6.0    54395.0  2020      9    1     1
246 2020-09-02      975.0         8.0        NaN  2020      9    2     2
247 2020-09-03     1326.0         6.0        NaN  2020      9    3     3

[248 rows x 8 columns]

In [85]:
# Q- query the rows for may

dataset_df_may = dataset_df[dataset_df["month"]== 5]                               # month is returned in numbers not by name
dataset_df

          date  new_cases  new_deaths  new_tests  year  month  day  week
0   2019-12-31        0.0         0.0        NaN  2019     12   31     1
1   2020-01-01        0.0         0.0        NaN  2020      1    1     2
2   2020-01-02        0.0         0.0        NaN  2020      1    2     3
3   2020-01-03        0.0         0.0        NaN  2020      1    3     4
4   2020-01-04        0.0         0.0        NaN  2020      1    4     5
..         ...        ...         ...        ...   ...    ...  ...   ...
243 2020-08-30     1444.0         1.0    53541.0  2020      8   30     6
244 2020-08-31     1365.0         4.0    42583.0  2020      8   31     0
245 2020-09-01      996.0         6.0    54395.0  2020      9    1     1
246 2020-09-02      975.0         8.0        NaN  2020      9    2     2
247 2020-09-03     1326.0         6.0        NaN  2020      9    3     3

[248 rows x 8 columns]

In [86]:
# Q- extract the subset of columns to be aggregated   -> and those col are new_cases , new_deaths , new_tests

dataset_df_subset = dataset_df[["new_cases" , "new_deaths" , "new_tests" ]]
dataset_df_subset

     new_cases  new_deaths  new_tests
0          0.0         0.0        NaN
1          0.0         0.0        NaN
2          0.0         0.0        NaN
3          0.0         0.0        NaN
4          0.0         0.0        NaN
..         ...         ...        ...
243     1444.0         1.0    53541.0
244     1365.0         4.0    42583.0
245      996.0         6.0    54395.0
246      975.0         8.0        NaN
247     1326.0         6.0        NaN

[248 rows x 3 columns]

In [87]:
# Q- get the column wise sum

dataset_df_subset_sum = dataset_df_subset.sum()
dataset_df_subset_sum
                                                                                            # .sum() -> can be used on individual column and also DF

new_cases      271754.5
new_deaths      35497.0
new_tests     4279456.0
dtype: float64

In [88]:
# combining all the above 3 individual tasks into one statement

dataset_df[dataset_df["month"]==5][["new_cases" , "new_deaths" , "new_tests"]].sum()

new_cases       29073.0
new_deaths       5658.0
new_tests     1078720.0
dtype: float64

In [89]:
# Q- check if no. of cases reported on sunday is higher than the avg no. of cases reported every day
dataset_df[dataset_df["day"]==6]                      # to find cases reported on sunday -> 6

          date  new_cases  new_deaths  new_tests  year  month  day  week
6   2020-01-06        0.0         0.0        NaN  2020      1    6     0
37  2020-02-06        0.0         0.0        NaN  2020      2    6     3
66  2020-03-06      769.0        41.0        NaN  2020      3    6     4
97  2020-04-06     4316.0       527.0        NaN  2020      4    6     0
127 2020-05-06     1075.0       236.0    37771.0  2020      5    6     2
158 2020-06-06      518.0        85.0    34036.0  2020      6    6     5
188 2020-07-06      192.0         7.0    13771.0  2020      7    6     0
219 2020-08-06      384.0        10.0    32169.0  2020      8    6     3

### finding average

In [90]:
                # finding avg

dataset_df_new_cases_avg = dataset_df["new_cases"].mean()
dataset_df_new_cases_avg

np.float64(1095.7842741935483)

In [91]:
# even we can give condition using .loc

dataset_df.loc[dataset_df["day"]==6 , "new_cases"]

6         0.0
37        0.0
66      769.0
97     4316.0
127    1075.0
158     518.0
188     192.0
219     384.0
Name: new_cases, dtype: float64

## Revision till now

In [92]:
# - to get full view of df instead of just few head or tails
# import pandas as pd
# from IPython.display import display
# with pd.option_context("display.max_rows",100):
#       display(df[df.colname>value]) 

# adding col to dataset  -> df["colname"] = val

# removing col -> df.drop(columns=["colname"],inplace=True or False)  true-> make changes in original DF , flase -> returns new df with changes

# sorting rows -> df.sort("colname",ascending = True or False).head(n) -> true-> reurns ascending order , false-> return descending order

#ways to deal with  null values-> 
        # replace with 0
        # replace with avg of entire col
        # replace with avg of prev and next values
        # discard that particular row completely

# modifying row in dataset or df -> df.at[rowno,"colname"] = df.at[rowno,"col"] operator df.at[rowno,"col"]   

# multiple conditions ->  df [df["colname"]==6] & df[["col1","col2","col3"]].sum()     
                            #OR
# df.loc(df[row pe conditon,"jis col pe lgani hai"]

# taking sum of values in a col -> df["colname"].sum()
# for all col in a df -> df.sum() 

# working with timeline -> we use DatetimeIndex class
            # df["yr"] = pd.DatetimeIndex(df["col"]).year
            # df["month"] = pd.DatetimeIndex(df["col"]).month
            # df["day"] = pd.Dtaetimeindex([df["col"]).day
            # df["week"] = pd.DatetimeIndex(df["col").weekday

# execution order -> pandas first evaluate conditions -> then filter rows -> then seslect columns

# also condition on rows and col can be applied using .loc -> df.loc[ row condition mtlb jo rows chahiye , "kis col me condition lgani hai"]

# finding average - >  df.colname.mean()

## Grouping and Aggregation

In [100]:
# seeing the data monthly wise

# s1. making monthly grpoups

dataset_by_months_grp = dataset_df.groupby("month")                 # 1st - grouping

In [101]:
# s2. aggregation

dataset_by_months_grp[["new_cases","new_deaths","new_tests"]].sum()       # 2nd - column selection  - same flow as in sql

       new_cases  new_deaths  new_tests
month
1            3.0         0.0        0.0
2          885.0        21.0        0.0
3       100851.0     11570.0        0.0
4       101852.0     16091.0   419591.0
5        29073.0      5658.0  1078720.0
6         8011.5      1404.0   830354.0
7         6722.0       388.0   797692.0
8        21060.0       345.0  1098704.0
9         3297.0        20.0    54395.0
12           0.0         0.0        0.0

In [105]:
# what were the average no. of cases , deaths, tests weekly

weekly_grp = dataset_df.groupby("week")

weekly_grp[["new_cases","new_deaths","new_tests"]].mean()

        new_cases  new_deaths     new_tests
week
0     1109.142857  124.800000  19826.700000
1      918.638889  129.944444  31166.900000
2      927.305556  144.750000  34665.210526
3     1095.666667  141.472222  34488.578947
4     1189.714286  144.885714  39225.684211
5     1192.642857  157.000000  34589.473684
6     1247.257143  159.457143  28588.105263

### .cumsum()  -> cumulative sum -> to calc running or cumulative sum of cases , deaths , tests up to the current date for each row
- to understand , ki is din tk kitna average hua ya iske pehel tk kitna hua

In [106]:
# let's add columns like total_cases , total_deaths , total_tests

dataset_df["total_cumulative_cases"]= dataset_df["new_cases"].cumsum()

In [108]:
dataset_df["total_cumulative_death"] = dataset_df["new_cases"].cumsum()

In [112]:
dataset_df["total_cumulative_tests"] = dataset_df["new_tests"].cumsum()

In [113]:
dataset_df

,date,new_cases,new_deaths,new_tests,year,month,day,week,total_cases,total_cumulative_death,total_cumulative_tests
0,2019-12-31,0.0,0.0,NaN,2019,12,31,1,0.0,0.0,NaN
1,2020-01-01,0.0,0.0,NaN,2020,1,1,2,0.0,0.0,NaN
2,2020-01-02,0.0,0.0,NaN,2020,1,2,3,0.0,0.0,NaN
3,2020-01-03,0.0,0.0,NaN,2020,1,3,4,0.0,0.0,NaN
4,2020-01-04,0.0,0.0,NaN,2020,1,4,5,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
243,2020-08-30,1444.0,1.0,53541.0,2020,8,30,6,267092.5,267092.5,4182478.0
244,2020-08-31,1365.0,4.0,42583.0,2020,8,31,0,268457.5,268457.5,4225061.0
245,2020-09-01,996.0,6.0,54395.0,2020,9,1,1,269453.5,269453.5,4279456.0
246,2020-09-02,975.0,8.0,NaN,2020,9,2,2,270428.5,270428.5,NaN
247,2020-09-03,1326.0,6.0,NaN,2020,9,3,3,271754.5,271754.5,NaN

### merging columns from one dataset to other

In [ ]:
#    merged_df = df1.merge(df2.on="colname)

### at last create a result_df including columns that are useful

In [114]:
#  result_df = dataset_df[["col1","col2",---]]

### to save dataframe to a file

In [115]:
# result_df.to_csv("csv_file_name",index=None)        # index = None or False -> to not get the additonal column of showing indexes